# Generated by Django 5.0.3 on 2024-03-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_primer_nombre', models.CharField(max_length=50, verbose_name="Person's first name")),
                ('per_segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name="Person's second name")),
                ('per_primer_apellido', models.CharField(max_length=50, verbose_name="Person's first last name")),
                ('per_segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name="Person's second last name")),
                ('per_email', models.EmailField(max_length=254, verbose_name="Person's email")),
                ('per_telefono', models.PositiveBigIntegerField(verbose_name="person's phone number")),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del material ')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_nit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prov_razon_social', models.CharField(max_length=50, verbose_name='Razón social del proveedor')),
                ('prov_telefono', models.BigIntegerField(verbose_name='Teléfono del proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('crud.persona',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='crud.persona')),
                ('emp_cedula', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name="Employee's id")),
                ('emp_cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name="Employee's job")),
                ('emp_salario', models.PositiveIntegerField(blank=True, null=True, verbose_name="Employee's salary")),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            bases=('crud.persona',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('pro_precio', models.IntegerField(verbose_name='Precio del producto')),
                ('pro_stock', models.IntegerField(verbose_name='Stock del producto')),
                ('pro_img', models.ImageField(upload_to='static/img/EDITADAS/nuevas')),
                ('materiales', models.ManyToManyField(to='crud.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='mat_prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.proveedor'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_comentario', models.CharField(max_length=150, verbose_name="Client's comment")),
                ('con_cli_per_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.cliente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'EConsultas',
            },
        ),
    ]
