# Generated by Django 5.0.3 on 2024-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_consulta_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pro_img',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
